printWidth: 80
tabWidth: 2
useTabs: false
singleQuote: false
semi: true
trailingComma: "all"
bracketSpacing: true
bracketSameLine: false
arrowParens: "always"
vueIndentScriptAndStyle: false
endOfLine: "lf"
